### PR TITLE
Hosts files generation

### PR DESCRIPTION
**Pull request by szedlakmate**
This is an initial work to support ad-blocker like AdAway by converting domains files into hosts files (adding "127.0.0.1 " before the actual domain)

This PR should resolve https://github.com/AmnestyTech/investigations/issues/4

### CODE REVIEW

**Comment by szedlakmate** [comment]
Before merging, it is certainly important to set up a Github action which verifies that the hosts files were re-generated if the corresponding domains file got updated

**Comment by botherder** [comment]
Personally I think we should avoid having investigations folders contain scripts to generate the files. If at all, we should have these scripts (including `generate_stix2.py`) in a separate dedicated `scripts` folder.

**Comment by originalsouth** [comment]
Something similar here https://github.com/originalsouth/NSOMet while we wait

**Comment by Te-k** [comment]
Hi,

We are providing indicators of compromise that may or may not be relevant for blocking and blocking formats can be very different. Thus we have no intention to maintain hosts files or other blocklist. If this is useful for you, feel free to do that in another repository. Thanks !

**Pull request closed without merging**
